name: Check
on:
  push:
    branches:
      - master
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      env_name_repo: ${{ vars.NAME_REPO }}

    steps:
      - name: set outputs
        id: export
        run: |
          echo "user=lashkapashka" >> $GITHUB_OUTPUT
          echo "front=test-devops-front" >> $GITHUB_OUTPUT
          echo "api=test-devops-api" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.env_name_repo }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Frontend Docker image
        run: |
          docker build -t ${{ env.env_name_repo }}/${{ steps.export.outputs.user }}/${{ steps.export.outputs.front }}:latest -f ./front/Dockerfile .
          docker push ${{ env.env_name_repo }}/${{ steps.export.outputs.user }}/${{ steps.export.outputs.front }}:latest

      - name: Build and push Backend Docker imag
        run: |
          docker build -t ${{ env.env_name_repo }}/${{ steps.export.outputs.user }}/${{ steps.export.outputs.api }}:latest -f ./api/Dockerfile .
          docker push ${{ env.env_name_repo }}/${{ steps.export.outputs.user }}/${{ steps.export.outputs.api }}:latest
  
  notify:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHATID_TO }}
          message: |
            The build was successful!
